// packages/storyboard-ui-vue/src/components/ConversationalSelect.vue
<template>
  <div class="select-root">
    <span class="select" @click="setXYThenToggle" data-cy-select>
      <mdc-body class="select-value">{{valueDisplay}}</mdc-body>
      <mdc-caption data-cy-select-label>{{label}}</mdc-caption>
    </span>

    <!-- <portal to="modal" v-if="showOptions"> -->
    <sk-portal v-if="showOptions">
      <transition appear name="fade">
        <div
          class="modal-background"
          :style="`
            --x: ${x}px;
            --y: ${y}px;
            --max-width: ${maxWidth}vw;
          `"
          @click="toggleOptions"
        >
          <div class="spacer-left"></div>
          <transition appear name="open">
            <div class="option-menu">
              <ul ref="options" key="options" class="options" data-cy-options>
                <li
                  v-for="({id, label, selected, faded}, index) of options"
                  :key="index"
                  class="option"
                  @click.stop="handleSelect(id)"
                >
                  <sk-chip :color="selected ? 'secondary' : undefined" :faded="faded">{{ label }}</sk-chip>
                </li>
              </ul>
              <mdc-fab class="options-button" icon="check" @click.stop="toggleOptions"></mdc-fab>
            </div>
          </transition>
          <div class="spacer-right"></div>
        </div>
      </transition>
    </sk-portal>
    <!-- </portal> -->
  </div>
</template>

<style scoped>
.select-root {
  display: inline-block;
}
.select {
  background: linear-gradient(
      rgba(255, 255, 255, var(--overlay-strength)),
      rgba(255, 255, 255, var(--overlay-strength))
    ),
    var(--mdc-theme-secondary);
  border-radius: var(--border-radius);
  margin: 0.25rem auto;
  padding: calc(2 * var(--padding-increment)) calc(3 * var(--padding-increment));
  display: inline-flex;
  flex-flow: column nowrap;
}

.select-value {
  color: var(--mdc-theme-secondary);
  font-weight: bold;
  text-align: center;
  /* font-size: inherit; */
  box-sizing: border-box;
  margin: 0;
  /* padding: var(--padding-increment) 0; */
  border-left: none;
  border-top: none;
  border-right: none;
  border-bottom: var(--stroke-increment) dotted var(--mdc-theme-secondary);
}

.modal-background {
  --x: 0px;
  --y: 0px;
  --max-width: 88%;
  --half-max-width: calc(var(--max-width) / 2);

  pointer-events: initial;
  /* max-width: 100vw; */
  min-height: 100vh;
  background: #ffffff; /* Currently white, maybe should be theme background-color? */
  opacity: var(--opacity);
  display: flex;
  align-items: flex-start;
  padding-top: var(--y);
}

.spacer-left {
  flex: 1 10000 calc(var(--x) - var(--half-max-width));
}

.option-menu {
  max-width: var(--max-width);
  flex: 0 1 auto;
  display: flex;
  flex-flow: column nowrap;
  align-items: center;
}

.spacer-right {
  flex: 1 1000 calc(100vw - var(--x) - var(--half-max-width));
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 400ms;
}

.fade-enter,
.fade-leave-to {
  opacity: 0;
}

.options {
  padding: 0;
  list-style-type: none;
  position: relative;
  display: inline-flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
  pointer-events: none;
  transform: scale(1);
}

.option {
  pointer-events: initial;
  margin: calc(var(--padding-increment) / 2);
}

.options-button {
  transform: scale(1);
}

.open-enter-active,
.open-leave-active {
  transition: transform 300ms cubic-bezier(0.68, -0.55, 0.265, 1.55);
  transform-origin: top center;
}

.open-enter,
.open-leave-to {
  transform: scale(0);
}
</style>

<script>
import {
  createLabelString,
  getBottomY,
  getMaxWidth
} from "../../../components-svelte/src/utilities/general";

/**
 * When I get GAS code-splitting to work I should asynchronously load all these
 *
 * MdcFab is a bit odd, you need to pull the named export out.
 * E.g.:
 * ```
 * MdcFab: async () => {
 *  const MdcFAB = await import('vue-mdc-adapter/dist/fab')
 *  return MdcFAB.mdcFAB
 * }
 * ```
 */
import SkChip from "./SkChip.vue";
import { mdcFAB as MdcFab } from "vue-mdc-adapter/dist/fab";
import SkPortal from "./SkPortal.vue";
import { setSelected } from '../scripts/sk';

export default {
  components: {
    SkChip,
    MdcFab,
    SkPortal
  },
  props: {
    label: {
      type: String,
      default: "Select something"
    },
    placeholder: {
      type: String,
      default: "any"
    },
    options: {
      type: Array,
      required: true
    },
    displayFn: {
      type: Function,
      default: createLabelString("or")
    },
    onSelect: {
      type: Function,
      default: () => {}
    }
  },
  data: () => ({
    x: 0,
    y: 0,
    maxWidth: 88,
    showOptions: false
  }),
  computed: {
    valueDisplay() {
      const selections = this.options.filter(({ selected }) => selected);
      if (selections.length) {
        const labels = selections.map(({ label }) => label);
        return this.displayFn(...labels);
      } else {
        return this.placeholder;
      }
    }
  },
  methods: {
    toggleOptions() {
      this.showOptions = !this.showOptions;
    },
    setXYThenToggle(e) {
      this.x = e.clientX;
      this.y = getBottomY(e.target);
      this.toggleOptions();
    },
    handleSelect(selection) {
      const setSelectedOption = setSelected(selection)
      const newOptions = this.options.map(setSelectedOption)
      this.$emit("selected", { value: newOptions });
    }
  },
  mounted() {
    const deviceWidth = window.innerWidth;
    this.maxWidth = getMaxWidth(deviceWidth);
  }
};
</script>

// packages/ui-components-svelte/src/components/inputs/ConversationalSelect.svelte
<svelte:options tag="conversational-select" />

<script>
  import { onMount, beforeUpdate, createEventDispatcher } from 'svelte'
  import { backInOut } from 'svelte/easing'
  import Modal from "../Modal.svelte";
  import Chip from "../Chip.svelte";
  import IconButton from './IconButton.svelte'
  import { createLabelString } from "../../utilities/general.js";

  export let label = "";
  export let placeholder = "any";
  export let valueDisplayHandler = createLabelString('or')

  /**
   * `Select` component
   * 
   * Currently this does not actually have internal state.
   * I was getting infinite loops with 2-way binding, so I 
   * switched to just sending an event up.
   * 
   * The only way to change the values are to have the parent
   * handle the event and update the `options` prop.
   * 
   * In the future, we can:
   * 
   * 1. Add a `localOptions` aka `selectedValues` or something and 
   *    update it to reflect options whenever options changes. We
   *    can use a reactive statement for this, I think.
   * 
   * 2. (Preferred) Get 2-way binding to work with a hidden <select> element.
   */

  // options = [
  //   {
  //     id: string,
  //     label: string,
  //     selected: boolean
  //   }
  // ]
  export let options = [];
  
  let control
  let optionSet
  let showModal = false

  /**
   * Selection handling
   */
  const dispatch = createEventDispatcher()
  const handleSelect = (id) => () => {
    const newOptions = options.map( (option) => option.id === id ? { ...option, selected: !option.selected } : option )
    dispatch('selected', {
      value: newOptions
    })
  }

  $: selectedValues = options.filter( ({ selected }) => selected )
  $: labels = selectedValues.map(val => val.label);
  $: valueDisplay = selectedValues.length ? valueDisplayHandler(...labels)
                                        : emptyValueLabel

  /**
   * Option Set rendering
   */
  let x = 0

  // rect is undefined until control is rendered.
  $: rect = control && control.getBoundingClientRect()
  $: y = rect && rect.y + rect.height

  // scale is used in inline CSS to set the transform to scale(1)
  $: scale = +showModal

  const toggleModal = () => showModal = !showModal

  const setXOnClick = (e) => {
    x = e.screenX
  }

  const setOptionPlacement = (optionSet, xPos, yPos) => {
    const style = optionSet.style
    style.setProperty('--x', `${xPos}px`)
    style.setProperty('--y', `${yPos}px`)
  }

  const handleUpdate = () => {
    /**
     * beforeUpdate() runs once before the component ever mounts.
     * 
     * Additionally, optionSet will conditionally not exist.
     */
    if (optionSet) {
      setOptionPlacement(optionSet, x, y)
    }    
  }

  beforeUpdate(handleUpdate)

  const open = (node, { duration = 400 }) => {
    const css = (t) => {
      const eased = backInOut(t)
      return `transform: scale(${eased}) translateX(-50%);`
    }

    return {
      duration,
      css
    }
  }
</script>

<style>
  .select {
    background: var(--secondary-color-very-light-background);
    border-radius: var(--border-radius);
    padding: calc(2 * var(--padding-increment))
      calc(3 * var(--padding-increment));
    display: inline-flex;
    flex-flow: column nowrap;
  }

  .select-value {
    font-family: var(--typo-body-font-family);
    font-weight: bold;
    color: var(--secondary-color);
    text-align: center;
    /* font-size: inherit; */
    box-sizing: border-box;
    padding: var(--padding-increment) 0;
    border-left: none;
    border-top: none;
    border-right: none;
    border-bottom: var(--stroke-increment) dotted var(--secondary-color);
  }

  .select-label {
    font-family: var(--typo-display-font-family);
    font-size: 1rem;
    font-weight: normal;
    color: var(--text-color-dark);
  }

  .options-set {
    --x: 0px;
    --y: 0px;
    position: relative;
    top: var(--y);
    left: var(--x);
    transform-origin: top left;
    transform: scale(1) translateX(-50%);
    display: inline-flex;
    flex-flow: column nowrap;
    align-items: center;
    pointer-events: none;
  }

  .options-set :global(.options-button) {
    margin-top: var(--padding-increment);
  }

  .options-chips {
    display: flex;
    flex-wrap: wrap;
    pointer-events: initial;
  }

  .options-set, .options-chips {
    justify-content: center;
  }

  .options-chips > :global(*)  {
    margin: calc(var(--padding-increment) / 2);
  }
</style>


<!-- 
  #TODO switch to using a hidden <select> element and binding the value.

  - Better for accessibility
  - More "right"
  - Can use Svelte's 2-way binding, if I can get it to work
-->
<!-- <select></select> -->

<span bind:this={control} class="select" on:click={setXOnClick} on:click={toggleModal} data-cy-select >
  <div class="select-value">{valueDisplay}</div>
  <div class="select-label" data-cy-select-label>{label}</div>
</span>

{#if showModal}
<Modal on:click={toggleModal}>
  <div class="options-set" bind:this={optionSet} transition:open>
    <div class="options-chips" data-cy-options-chips>
      {#each options as option, index (option.id)}
        <Chip on:click={handleSelect(option.id)} selected={option.selected}>{option.label}</Chip>
      {/each}
    </div>
    <IconButton class="options-button" color="secondary" on:click={toggleModal}>✔</IconButton>
  </div>
</Modal>
{/if}
